services:
  mongo:
    image: mongo:8.0
    container_name: unifidb
    pull_policy: always
    restart: unless-stopped

  unifi:
    image: ghcr.io/goofball222/unifi
    container_name: unifi
    pull_policy: always
    restart: unless-stopped
    links:
      - mongo
    ports:
      - 3478:3478/udp
      - 8080:8080
      - 8443:8443
      - 8880:8880
      - 8843:8843
#     Optional: Uncomment to enable speed tests from the UniFi iOS & Android apps
      - 6789:6789
#     Optional: Uncomment for layer 2 broadcast discovery if container running on a host in the local LAN
      - 10001:10001/udp
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - DB_MONGO_LOCAL=false
      - DB_MONGO_URI=mongodb://mongo:27017/unifi
      - STATDB_MONGO_URI=mongodb://mongo:27017/unifi_stat
      - TZ=UTC
      - UNIFI_DB_NAME=unifi
